# ============================================================================
# WeikongPC Setup Helper (setup-helper.ps1)
# Called by Inno Setup installer
# Functions:
#   - Get CPU/Motherboard serial, SHA-256 hash to generate 32-char uid
#   - Generate 16-char random key
#   - Write WeikongPC.ini (with server_url, uid, uid_key, os)
#   - Call GoQR.me API to generate QR code for ini content
# Note: Service registration is handled by WeikongPC.exe install/uninstall
# ============================================================================
param(
    [Parameter(Mandatory=$true)]
    [ValidateSet("install", "repair", "uninstall")]
    [string]$Mode,

    [Parameter(Mandatory=$true)]
    [string]$InstallPath,

    [string]$QrOutputPath
)

$ErrorActionPreference = "Stop"

function Write-Log {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "[$timestamp] $Message"
}

function Get-CpuSerial {
    try {
        $cpu = Get-CimInstance -ClassName Win32_Processor -ErrorAction Stop | Select-Object -First 1
        if ($cpu.ProcessorId -and $cpu.ProcessorId.Trim().Length -gt 0) {
            return $cpu.ProcessorId.Trim()
        }
    } catch {}
    return "CPU_UNKNOWN"
}

function Get-MotherboardSerial {
    try {
        $mb = Get-CimInstance -ClassName Win32_BaseBoard -ErrorAction Stop | Select-Object -First 1
        if ($mb.SerialNumber -and $mb.SerialNumber.Trim().Length -gt 0) {
            return $mb.SerialNumber.Trim()
        }
    } catch {}
    return "MB_UNKNOWN"
}

function Compute-Uid {
    param([string]$CpuSerial, [string]$MotherboardSerial)
    $raw = "$CpuSerial|$MotherboardSerial"
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($raw)
    $sha = [System.Security.Cryptography.SHA256]::Create()
    $hash = $sha.ComputeHash($bytes)
    $hex = -join ($hash | ForEach-Object { $_.ToString("x2") })
    return $hex.Substring(0, 32)
}

function New-RandomKey {
    $chars = "abcdefghijkmnpqrstuvwxyzABCDEFGHJKMNPQRSTUVWXYZ23456789"
    $random = New-Object System.Random
    $key = ""
    for ($i = 0; $i -lt 16; $i++) {
        $key += $chars[$random.Next(0, $chars.Length)]
    }
    return $key
}

function Generate-QrCode {
    param([string]$Content, [string]$OutputPath)
    $encoded = [uri]::EscapeDataString($Content)
    $apiUrl = "https://api.qrserver.com/v1/create-qr-code/?data=$encoded&size=300x300&margin=10"
    try {
        Write-Log "Generating QR code: $OutputPath"
        Invoke-WebRequest -Uri $apiUrl -OutFile $OutputPath -TimeoutSec 30 -UseBasicParsing
        return $true
    } catch {
        Write-Log "QR generation failed: $($_.Exception.Message)"
        return $false
    }
}

function Write-IniFile {
    param(
        [string]$Path,
        [string]$Uid,
        [string]$UidKey,
        [string]$Os
    )
    $content = @"
; ============================================================================
; WeikongPC Client Config (WeikongPC.ini)
; Same directory as WeikongPC.exe. Auto-generated by installer.
; ============================================================================

[server]
url=https://weikongpc.com/beat

[device]
uid=$Uid
uid_key=$UidKey
os=$Os
"@
    Set-Content -Path $Path -Value $content -Encoding UTF8
    Write-Log "Wrote config: $Path"
}

Write-Log "=========================================="
Write-Log "WeikongPC setup helper started"
Write-Log "Mode: $Mode, InstallPath: $InstallPath"
Write-Log "=========================================="

switch ($Mode) {
    "install" {
        $cpuSerial = Get-CpuSerial
        Write-Log "CPU serial: $cpuSerial"
        $mbSerial = Get-MotherboardSerial
        Write-Log "Motherboard serial: $mbSerial"

        $uid = Compute-Uid -CpuSerial $cpuSerial -MotherboardSerial $mbSerial
        Write-Log "Generated uid: $uid"
        $uidKey = New-RandomKey
        Write-Log "Generated key: $uidKey"
        $os = (Get-CimInstance Win32_OperatingSystem).Caption
        Write-Log "OS: $os"

        $iniPath = Join-Path $InstallPath "WeikongPC.ini"
        Write-IniFile -Path $iniPath -Uid $uid -UidKey $uidKey -Os $os

        if ($QrOutputPath) {
            $qrContent = "uid=$uid`nkey=$uidKey"
            Generate-QrCode -Content $qrContent -OutputPath $QrOutputPath
        }

        Write-Log "Config generation complete: uid=$uid, key=$uidKey"
        Write-Output "UID=$uid"
        Write-Output "KEY=$uidKey"
    }
    "repair" {
        $cpuSerial = Get-CpuSerial
        $mbSerial = Get-MotherboardSerial
        $uid = Compute-Uid -CpuSerial $cpuSerial -MotherboardSerial $mbSerial
        $uidKey = New-RandomKey
        $os = (Get-CimInstance Win32_OperatingSystem).Caption

        $iniPath = Join-Path $InstallPath "WeikongPC.ini"
        Write-IniFile -Path $iniPath -Uid $uid -UidKey $uidKey -Os $os

        if ($QrOutputPath) {
            $qrContent = "uid=$uid`nkey=$uidKey"
            Generate-QrCode -Content $qrContent -OutputPath $QrOutputPath
        }

        Write-Log "Repair complete: uid=$uid, key=$uidKey"
        Write-Output "UID=$uid"
        Write-Output "KEY=$uidKey"
    }
    "uninstall" {
        # Nothing to do here; service unregister is handled by WeikongPC.exe uninstall
        Write-Log "Uninstall mode: nothing to do (service handled by WeikongPC.exe uninstall)"
    }
}